In [1]:
import pandas as pd
df1=pd.read_csv('jobs.csv')
df2=pd.read_csv('hh_kz_astanavacancies.csv')
df3=pd.read_csv('hh_kz_almatyvacancies_.csv')

In [3]:
df_all=pd.concat([df1, df2, df3])

In [4]:
df_all

,name,company,salary_from,salary_to,currency,city,url,description,skills,id,title,company_id,experience,employment,schedule,requirement,responsibility,published_at
0,Стажер-разработчик,Prime Source,200000.0,250000.0,KZT,Алматы,https://hh.ru/vacancy/131896635,<strong>Обязанности:</strong> <ul> <li>Разрабо...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Data аналитик (Астана),Profit services,NaN,NaN,NaN,Астана,https://hh.ru/vacancy/131896589,<strong>Обязанности:</strong> <ul> <li> <p><st...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Backend Developer (Python, Django)",My Startups,NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131872138,<strong>Требования:</strong> <p><strong>Общие ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Backend разработчик,Amir Zhoba,700000.0,800000.0,KZT,Алматы,https://hh.ru/vacancy/131694892,<p>Мы ищем сильного разработчика уровня крепки...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DevOps Engineer,MYTONA KZ,NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131893632,"<p>Ищем <strong>DevOps</strong> инженера, кото...","Kubernetes, Docker",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2707,NaN,Richfit International,NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131722376,NaN,NaN,131722376.0,Старший консультант модуля SAP FI,1919301.0,От 3 до 6 лет,Полная занятость,Полный день,...SAP модуле FI от 3 лет и более. Не менее 1 ...,Сбор требований и разработка проектных решений...,2026-04-01T08:07:56+0300
2708,NaN,Inkar,NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131658063,NaN,NaN,131658063.0,Главный бухгалтер управляющей компании,107982.0,От 3 до 6 лет,Полная занятость,Полный день,NaN,Прохождение внутренних и внешних аудиторских п...,2026-03-30T11:36:23+0300
2709,NaN,"Danone, ТМ",NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131421242,NaN,"МСФО, Финансовый контроль, Управленческая отче...",131421242.0,Senior Financial control manager/Chief Account...,135408.0,Более 6 лет,Полная занятость,Полный день,Отличное знание бухгалтерского и налогового за...,Постановка и отладка бухгалтерского учета по н...,2026-03-20T14:19:58+0300
2710,NaN,"Danone, ТМ",NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131343981,NaN,"Исполнительность, Ответственность, Ориентация ...",131343981.0,HR Generalist,135408.0,От 3 до 6 лет,Полная занятость,Полный день,В этой роли ты будешь: Высшее образование (жел...,Участвовать во всех ключевых HR-процессах: под...,2026-03-18T13:39:21+0300
2711,NaN,"ЕвроХим, Минерально-Химическая Компания",NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131324265,NaN,"Подготовка юридических заключений, Учредительн...",131324265.0,Главный юрисконсульт,2501.0,Более 6 лет,Полная занятость,Полный день,"Гражданское право, включая корпоративное, дого...","Подготовка и внедрение политик, стандартов, ре...",2026-03-18T08:23:56+0300

In [7]:
df_all.duplicated('url').sum()

np.int64(0)

In [6]:
df_all.drop_duplicates(subset=['url'], inplace=True)

In [25]:
df

,name,company,salary_from,salary_to,currency,city,url,description,skills,employment,schedule,published_at
0,Стажер-разработчик,Prime Source,200000.0,250000.0,KZT,Алматы,https://hh.ru/vacancy/131896635,"Обязанности: Разработка, развитие и поддер...",NaN,NaN,NaN,NaN
1,Data аналитик (Астана),Profit services,NaN,NaN,NaN,Астана,https://hh.ru/vacancy/131896589,Обязанности: Сбор и подготовка данных: ...,NaN,NaN,NaN,NaN
2,"Backend Developer (Python, Django)",My Startups,NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131872138,Требования: Общие требования: Опыт ком...,NaN,NaN,NaN,NaN
3,Backend разработчик,Amir Zhoba,700000.0,800000.0,KZT,Алматы,https://hh.ru/vacancy/131694892,Мы ищем сильного разработчика уровня крепкий M...,NaN,NaN,NaN,NaN
4,DevOps Engineer,MYTONA KZ,NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131893632,"Ищем DevOps инженера, который будет развиват...","Kubernetes, Docker",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2707,Старший консультант модуля SAP FI,Richfit International,NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131722376,\n\n...SAP модуле FI от 3 лет и более. Не мене...,NaN,Полная занятость,Полный день,2026-04-01T08:07:56+0300
2708,Главный бухгалтер управляющей компании,Inkar,NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131658063,\n\n\n\nПрохождение внутренних и внешних аудит...,NaN,Полная занятость,Полный день,2026-03-30T11:36:23+0300
2709,Senior Financial control manager/Chief Account...,"Danone, ТМ",NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131421242,\n\nОтличное знание бухгалтерского и налоговог...,"МСФО, Финансовый контроль, Управленческая отче...",Полная занятость,Полный день,2026-03-20T14:19:58+0300
2710,HR Generalist,"Danone, ТМ",NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131343981,\n\nВ этой роли ты будешь: Высшее образование ...,"Исполнительность, Ответственность, Ориентация ...",Полная занятость,Полный день,2026-03-18T13:39:21+0300
2711,Главный юрисконсульт,"ЕвроХим, Минерально-Химическая Компания",NaN,NaN,NaN,Алматы,https://hh.ru/vacancy/131324265,"\n\nГражданское право, включая корпоративное, ...","Подготовка юридических заключений, Учредительн...",Полная занятость,Полный день,2026-03-18T08:23:56+0300

In [9]:
df1.columns

Index(['name', 'company', 'salary_from', 'salary_to', 'currency', 'city',
       'url', 'description', 'skills'],
      dtype='object')

In [10]:
df2.columns

Index(['id', 'title', 'city', 'company', 'company_id', 'experience',
       'employment', 'schedule', 'salary_from', 'salary_to', 'currency',
       'skills', 'requirement', 'responsibility', 'url', 'published_at'],
      dtype='object')

In [11]:
df_all['name']=df_all['name'].fillna(df_all['title'])

In [24]:
df.drop(columns=['responsibility', 'requirement'], inplace=True)

In [14]:
df=df_all

In [16]:
df1['description'].head(5).to_list()

['<strong>Обязанности:</strong> <ul> <li>Разработка, развитие и поддержка Аналитической системы</li> </ul> <strong>Требования:</strong> <ul> <li>Знание основ программирования</li> <li>Знания любого языка программирования (JavaScript, PHP, Python, C#, Java, C, C++ и др)</li> <li>Писать код, понимать основные принципы разработки ПО</li> <li>Быть знакомым с алгоритмами и типами переменных</li> <li>Преимуществом будет:</li> <li>Образование техническое, в области математики, физики</li> <li>Базовые знания SQL</li> <li>Наличие собственных проектов</li> </ul> <strong>Условия:</strong> <ul> <li>Оплата на стажировке 200 000 тенге</li> <li>Оплата после стажировки 250 000 тенге</li> </ul>',
 '<strong>Обязанности:</strong> <ul> <li> <p><strong>Сбор и подготовка данных:</strong> извлечение, очистка, интеграция, контроль качества.</p> </li> <li> <p><strong>Работа с БД:</strong> проектирование и оптимизация реляционных (PostgreSQL, MySQL) и OLAP-баз (ClickHouse), настройка в облаке GCP.</p> </li> <li> <p><strong>ETL и обработка:</strong> разработка и автоматизация процессов (Airflow, Docker, GCP), поддержка DAG-ов, мониторинг и алерты.</p> </li> <li> <p><strong>Аналитика:</strong> EDA, поиск паттернов, статистический анализ, сегментация, ad-hoc и post-launch аналитика.</p> </li> <li> <p><strong>Бизнес-аналитика:</strong> анализ ключевых метрик, построение бизнес-кейсов, прогнозирование влияния изменений на продуктовые показатели.</p> </li> <li> <p><strong>Отчётность и визуализация:</strong> создание витрин данных, дашбордов (Power BI, Tableau, Matplotlib, Plotly), автоматизация отчётности, презентация результатов.</p> </li> <li><strong>ML и моделирование: </strong>разработка и прототипирование моделей (включая NLP и BERT), построение предиктивных моделей.</li> </ul> <strong>Требования:</strong> <ul> <li> <p><strong>Опыт:</strong> 3+ года в проектах, связанных с данными (BI, DWH, аналитика, трансформация, governance).</p> </li> <li> <p><strong>Образование:</strong> высшее техническое (математика, информатика, статистика, экономика, инженерные специальности).</p> </li> <li> <p><strong>Языки и инструменты:</strong> Python (pandas, numpy, scikit-learn, TensorFlow/PyTorch), продвинутый SQL (joins, агрегации, оконные функции), Git, Linux, CI/CD.</p> </li> <li> <p><strong>Базы и инфраструктура:</strong> PostgreSQL, MySQL, ClickHouse, Oracle/Hive; понимание OLTP/OLAP, архитектур Data Lake / Data Warehouse; опыт с GCP/Azure; Docker, Airflow.</p> </li> <li> <p><strong>ML и DS: </strong>опыт обучения и внедрения моделей (NLP, CV, рекомендательные системы), работа с Transformers (BERT), знание ML-фундаментов и статистики.</p> </li> <li> <p><strong>Data Governance и процессы:</strong> опыт data profiling, анализа качества данных, source-to-target мэппингов; работа по Agile/Waterfall.</p> </li> <li> <p><strong>Визуализация:</strong> опыт с BI-инструментами (Power BI, Tableau, Looker), Excel/Google Sheets (сводные, формулы, макросы).</p> </li> <li><strong>Soft skills:</strong> аналитическое мышление, умение формализовать требования и доносить результаты бизнесу простым языком.</li> </ul>',
 '<strong>Требования:</strong> <p><strong>Общие требования:</strong></p> <ul> <li> <p>Опыт коммерческой разработки от 4 лет;</p> </li> <li> <p>Опыт работы с системами мониторинга и логирования;</p> </li> <li> <p>Умение писать чистый, поддерживаемый код;</p> </li> <li> <p>Опыт работы по Agile методологиям.</p> </li> </ul> <p> </p> <p><strong>Будет преимуществом:</strong></p> <ul> <li> <p>Опыт работы с FastAPI;</p> </li> <li> <p>Знание CQRS и Event Sourcing;</p> </li> <li> <p>Опыт работы с GitLab CI/CD;</p> </li> <li> <p>Опыт применения Zero Trust Architecture;</p> </li> <li> <p>Знание gRPC;</p> </li> <li> <p>Опыт работы с Hashicorp Vault;</p> </li> <li> <p>Практика работы с OpenTelemetry, Grafana Loki, Prometheus.</p> </li> </ul> <p> </p><br /><strong>Обязанности:</strong> <p><strong>Инфраструктура и DevOps:</strong></p> <ul> <li> <p>Уверенное владение Docker и Kubernetes;</p> </li> <li> <p>Опыт работы с облачными платформами (PS.kz, Yandex.Cloud);</p> </li> <li> <p>Понимание принципов отказоустойчивости и балансировки нагрузки (Nginx, HAProxy).</p> </li> </ul> <p> </p> <p><strong>Безопасность:</strong></p> <ul> <li> <p>Знание OWASP Top-10 и основных практик API Security;</p> </li> <li> <p>Опыт работы с OAuth2, JWT и современными протоколами аутентификации;</p> </li> <li> <p>Понимание основных принципов криптографии и безопасного хранения данных.</p> </li> </ul> <p> </p> <p><strong>Технический опыт:</strong></p> <ul> <li> <p>Уверенное владение Python 3.11+ и Django;</p> </li> <li> <p>Опыт проектирования и разработки REST API;</p> </li> <li> <p>Глубокое понимание SQL (PostgreSQL) и опыт работы с NoSQL решениями (MongoDB, Redis);</p> </li> <li> <p>Опыт работы с асинхронным программированием в Python (AsyncIO, Aiohttp);</p> </li> <li> <p>Практика построения монолоитной и микросервисной архитектуры и API-first подхода;</p> </li> <li> <p>Опыт работы с message broker системами (RabbitMQ).</p> </li> </ul><br /><p><strong>Условия:</strong></p> <ul> <li> <p>Служебная мобильная связь;</p> </li> <li> <p>Медицинское обслуживание;</p> </li> <li> <p>Гибридный формат работы;</p> </li> <li> <p>Абонемент на фитнес;</p> </li> <li> <p>Скидки на автомобильное обслуживание;</p> </li> <li> <p>Материальная помощь при личных событиях;</p> </li> <li> <p>Корпоративное обучение;</p> </li> <li> <p>Тимбилдинги.</p> </li> </ul>',
 '<p>Мы ищем сильного разработчика уровня крепкий Middle или Senior в команду для работы над современными IT-проектами.</p> <p>Обязанности:<br />• Разработка и поддержка backend-сервисов<br />• Проектирование и развитие API (REST / gRPC)<br />• Оптимизация производительности и масштабируемости системы<br />• Участие в архитектурных решениях<br />• Настройка и поддержка CI/CD процессов<br />• Деплой и сопровождение сервисов (prod / staging)<br />• Мониторинг, логирование и устранение инцидентов<br />• Взаимодействие с frontend-разработчиками, аналитиками и QA</p> <p>Проведение собрания с junior-разработчиками и стажёрами</p> <p>Требования:<br />• Уверенный опыт backend-разработки от 3 лет<br />• Отличное знание одного из языков: Python / Node.js / Go / Java<br />• Опыт работы с базами данных (PostgreSQL, MongoDB и др.)<br />• Понимание принципов построения микросервисной архитектуры<br />• Опыт работы с API и интеграциями<br />• Опыт настройки CI/CD<br />• Практический опыт работы с контейнерами и оркестрацией (Docker, Kubernetes)<br />• Опыт работы с Linux на уровне уверенного пользователя<br />• Понимание сетей (HTTP, DNS, TLS)</p> <p>Будет плюсом:<br />• Опыт работы с облачными платформами (Amazon Web Services, Google Cloud Platform, Microsoft Azure)<br />• Опыт построения отказоустойчивых систем<br />• Навыки инфраструктуры как кода (Terraform и др.)<br />• Опыт настройки мониторинга (Prometheus, Grafana)</p> <p>Условия:<br />• Влияние на архитектуру и технические решения<br />• Минимум бюрократии, быстрые релизы<br />• Конкурентная зарплата + бонусы<br />• Сильная команда и интересные задачи</p> <p>Компания предоставляет служебную развозку</p>',
 '<p>Ищем <strong>DevOps</strong> инженера, который будет развивать и масштабировать инфраструктуру, автоматизировать процессы и выстраивать стабильные CI/CD pipeline в продуктовой среде.</p> <p><br /><strong>Задачи:</strong></p> <ul> <li> <p>Автоматизация процессов pipeline</p> </li> <li> <p>Развитие и поддержка инфраструктуры</p> </li> <li> <p>Шаблонизация pipeline с учетом лучших практик</p> </li> <li> <p>Сопровождение и разработка Helm charts</p> </li> <li> <p>Администрирование систем логирования и мониторинга</p> </li> <li> <p>Работа с облачными провайдерами и обеспечение их устойчивой работы (CloudOps)</p> </li> </ul> <p><strong>Требования:</strong></p> <ul> <li> <p>Опыт работы в качестве DevOps от 2-х лет</p> </li> <li> <p>Опыт работы с Kubernetes и Docker</p> </li> <li> <p>Знание Helm и умение писать charts</p> </li> <li> <p>Знание и опыт работы с инструментами IaC: Terraform, Ansible</p> </li> <li> <p>Опыт работы с платформами CI/CD (Teamcity, Jenkins)</p> </li> <li> <p>Уверенные навыки администрирования Unix-систем</p> </li> <li> <p>Понимание сетевой архитектуры и принципов сетевой безопасности</p> </li> <li> <p>Опыт работы с облачными провайдерами, такими как AWS</p> </li> <li> <p>Опыт администрирования систем мониторинга и нотификации (Zabbix, Graylog, Grafana, Prometheus, ELK)</p> </li> <li> <p>Знание и опыт администрирования СУБД (SQL/NoSQL)</p> </li> <li> <p>Навыки разработки инструментов автоматизации</p> </li> <li> <p>Умение писать скрипты на bash/ python</p> </li> <li> <p>Базовые знания программирования</p> </li> </ul> <p><strong>Будет плюсом: </strong></p> <ul> <li>Опыт работы с Highload архитектурами</li> <li>Знание английского языка</li> </ul> <p><strong>Мы предлагаем:</strong></p> <ul> <li>Профессиональный и карьерный рост</li> <li>Удаленную работу</li> <li>Интересные задачи на международном уровне</li> <li>Медицинскую страховку, бонусы wellbeing и kids</li> <li>Программы внутреннего обучения</li> <li>Мероприятия и конференции</li> </ul>']

In [18]:
df2['responsibility'].head(5).to_list()

['Тестирование продуктовых фич с позиции Power BI аналитика. — Проверка логики решений (DAX, модели, метрики). — Выявление ошибок, неочевидных багов и “узких...',
 'Предиктивная аналитика: построение и внедрение ML-моделей (прогнозирование оттока, сегментация пользователей). Создание и поддержка ETL-процессов для автоматизации аналитики.',
 'Архитектура данных: проектирование схем событий, интеграция с Data Lake / DWH для near-realtime аналитики. Экосистемные интеграции. Инженерные стандарты: культура code...',
 'Отслеживание трендов в веб-дизайне, графическом дизайне и digital-среде. Тестирование и улучшение UX на основе аналитики и обратной связи.',
 'Анализ бизнес-процессов и формирование требований для разработки новых и доработки существующих систем. Сбор, анализ и документирование бизнес и системных...']

In [19]:
from bs4 import BeautifulSoup

def clean_html(text):
    if pd.isna(text):
        return ''
    return BeautifulSoup(text, "html.parser").get_text(separator=' ')

In [20]:
df['description'] = df['description'].apply(clean_html)

In [22]:
df['description'] = (
    df['description'].fillna('') + "\n\n" +
    df['requirement'].fillna('') + "\n\n" +
    df['responsibility'].fillna('')
)

In [28]:
df['published_at'] = pd.to_datetime(df['published_at']).dt.date

In [31]:
df['published_at'].unique()

array([NaT, datetime.date(2026, 4, 12), datetime.date(2026, 4, 9),
       datetime.date(2026, 4, 8), datetime.date(2026, 4, 13),
       datetime.date(2026, 4, 11), datetime.date(2026, 4, 10),
       datetime.date(2026, 4, 7), datetime.date(2026, 4, 6),
       datetime.date(2026, 4, 5), datetime.date(2026, 4, 3),
       datetime.date(2026, 4, 2), datetime.date(2026, 4, 1),
       datetime.date(2026, 3, 31), datetime.date(2026, 3, 30),
       datetime.date(2026, 3, 29), datetime.date(2026, 3, 28),
       datetime.date(2026, 3, 27), datetime.date(2026, 3, 26),
       datetime.date(2026, 3, 25), datetime.date(2026, 3, 24),
       datetime.date(2026, 3, 23), datetime.date(2026, 3, 20),
       datetime.date(2026, 3, 19), datetime.date(2026, 3, 18),
       datetime.date(2026, 3, 17), datetime.date(2026, 3, 16),
       datetime.date(2026, 4, 4), datetime.date(2026, 3, 22),
       datetime.date(2026, 3, 14), datetime.date(2026, 3, 15),
       datetime.date(2026, 3, 21)], dtype=object)

In [32]:
df.to_csv('jobs.csv', index=False)